call plug#begin('~/.vim/plugged')
  Plug 'Raimondi/delimitMate'                       "auto close quotes and brackets
  
  Plug 'mxw/vim-jsx'                                "JS sintax plugins
  Plug 'pangloss/vim-javascript'                    "JS sintax plugins
  Plug 'hail2u/vim-css3-syntax'                     "CSS styles syntax
  Plug 'jimeno0/vim-chito'                          "custom color scheme

  Plug 'scrooloose/nerdtree'                        "Files tree

  Plug 'w0rp/ale'                                   "lint

  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' } "FuzzyFinder 

  Plug 'mileszs/ack.vim'                            "Find in fliles with Ack
  Plug 'SirVer/ultisnips'                           "snippets
  Plug 'honza/vim-snippets'                         "snippets
call plug#end()

set nocompatible                                    "avoid vim try to be vi
syntax enable    
filetype plugin on                                  "filebrowsing that comes with vim
set path+=**                                        "set find files recursible
set wildmenu                                        "display al matches when hit tab
"set wildignore+=**/node_modules/**
"set wildignore+=**/.next/**
"set wildignore+=**/.git/**
"set wildignore+=**/.storybook/**
"set wildignore+=**/static/**

let $FZF_DEFAULT_COMMAND = 'ag -g ""'               "allow fuzzy finder to ingore gitignores
command F FZF


set background=dark                                 "Teme colors
set termguicolors
colorscheme chito
let g:jsx_ext_required = 0                          "JSX on all file exetensions


set nowritebackup                                   "do not make backups
set noswapfile
set nobackup

set autoread                                        "reload a file if it has change outside vim
set history=10000                                   "Limit history

let g:UltiSnipsExpandTrigger="<tab>"                "snippets config
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"

set laststatus=2                                    "always display statusbar

                                                    "better copy files ( to be able to do cmd+v)
noremap Y "*y
noremap y "*y
noremap yy "*yy

set nu relativenumber                                "show line number and relative line number
set scrolloff=5                                      "offset of 5 rows on scroll (top/button) 

set breakindent                                      "Mantain indent on wrapping lines
set autoindent                                       "autoindent
set tabstop=2 shiftwidth=2 expandtab softtabstop=2   "tabs = 2 spaces

set colorcolumn=120                                  "highligt 120 column
set cursorline                                       "hight cursor line

set hls                                              "highlight search matches
set is                                               "higlight on search
"clear hghlight on press enter normal mode
nnoremap <CR> :noh<CR><CR>  

"Linter config
let g:ale_linters = {
\   'javascript': ['eslint']
\}
let g:ale_sign_error = '💥'
let g:ale_fixers = {}
let g:ale_fixers.javascript = [
\ 'eslint',
\]
let g:ale_fix_on_save = 1


"remap leader key (default \) to ,a do a search on directory
let mapleader = ","
nmap <leader>a :Ack! --ignore-dir=node_modules --ignore-dir=.next --ignore-dir=dist --ignore-dir=build --ignore-dir=coverage --ignore-dir=src/messages ""<Left>

" Until today I used to use caps lock as ESC.
" From now using caps lock as ctrl and ctrl-c as ESC:
inoremap <C-c> <Esc>

" switch panes with ctrl jklh
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

